server:
  port: 8081

spring:
  application:
    name: p6spy-sample
  sleuth:
    enabled: false
    sampler:
      probability: 1
  datasource:
    initialization-mode: never
    hikari:
      pool-name: h2
      jdbc-url: jdbc:h2:mem:test-${random.int};DB_CLOSE_DELAY=-1
      username: sa
      password:
      maximum-pool-size: 10
  zipkin:
    enabled: false

decorator:
  datasource:
    datasource-proxy:
      logging: slf4j
      query:
        enable-logging: true
        logger-name:
        log-level: DEBUG
      slow-query:
        enable-logging: true
        logger-name:
        log-level: WARN
        threshold: 300
