server:
  port: 8081

spring:
  application:
    name: p6spy-sample
  sleuth:
    sampler:
      percentage: 1
  datasource:
    initialize: false

    dbcp2:
      url: jdbc:h2:mem:test-${random.int};DB_CLOSE_DELAY=-1
      username: sa
      password:
  zipkin:
    enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
